name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t spring-cicd . 
          docker tag spring-cicd yerinpark0208/spring-cicd:${GITHUB_SHA::7}
          docker push yerinpark0208/spring-cicd:${GITHUB_SHA::7}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 3.24.167.21
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull yerinpark0208/spring-cicd:${GITHUB_SHA::7}
            docker tag yerinpark0208/spring-cicd:${GITHUB_SHA::7} spring-cicd
            docker stop server
            docker rm -f server
            docker run -d --name server -p 8080:8080 spring-cicd
